spring.application.name=kintrahub-backend

spring.datasource.url=jdbc:mysql://localhost:3306/carebridge
spring.datasource.username=root
spring.datasource.password=2027
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.hibernate.ddl-auto=update

spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.show-sql=true
spring.web.resources.static-locations=file:uploads/
spring.jackson.deserialization.fail-on-unknown-properties=true

#Swagger link http://localhost:8080/swagger-ui.html

jwt.secret=c364cb7b1e072c20af408c432518e7d22380949fdee699640d86eb87a38a938a
jwt.expiration=7600000
